## GitLab CI
---
image: php:8.0-apache

stages:
    - setup

before_script:
  - apt-get update -yqq
  - apt-get upgrade -yqq
  - apt-get install -y nodejs

start:
    stage: setup
    script:
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        - php composer-setup.php --filename=composer
        - php -r "unlink('composer-setup.php');"
        - mv composer /usr/local/bin/
        - composer -v
        - npm i -g npm@latest yarn@latest

build:
    stage: setup
    cache:
        paths:
            - php_packages/
            - node_modules/
    script:
        - composer install --no-dev
        - composer run app
        - yarn install
        - yarn run app
